language: go

go:
  - 1.8.3

services:
  - postgresql

env:
  - POSTGRES_URL=postgres://postgres@localhost/sync?sslmode=disable

install:
  - go get -u -v github.com/haya14busa/goverage
  - go get -d -t -v ./...

before_script:
  - psql -c "CREATE DATABASE sync;" -U postgres
  - psql -d sync -af migrations/001_initial.up.sql -U postgres

script:
  - go build -v ./cmd/sync
  - goverage -v -race -coverprofile=coverage.out -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
