[[dependencies]]
  name = "github.com/dgrijalva/jwt-go"
  version = "^3.0.0"

[[dependencies]]
  name = "github.com/gorilla/mux"
  version = "^1.3.0"

[[dependencies]]
  branch = "master"
  name = "github.com/kat-co/vala"

[[dependencies]]
  branch = "master"
  name = "github.com/lib/pq"

[[dependencies]]
  branch = "master"
  name = "github.com/pkg/errors"

[[dependencies]]
  name = "github.com/satori/go.uuid"
  version = "^1.1.0"

[[dependencies]]
  branch = "master"
  name = "github.com/spf13/viper"

[[dependencies]]
  branch = "master"
  name = "github.com/urfave/negroni"

[[dependencies]]
  branch = "master"
  name = "github.com/vattle/sqlboiler"

[[dependencies]]
  branch = "master"
  name = "golang.org/x/crypto"

[[dependencies]]
  branch = "master"
  name = "golang.org/x/sys"

[[dependencies]]
  name = "gopkg.in/nullbio/null.v6"
  version = "^6.3.0"
