[[dependencies]]
  name = "github.com/dgrijalva/jwt-go"
  version = "^3.0.0"

[[dependencies]]
  name = "github.com/gorilla/mux"
  version = "^1.3.0"

[[dependencies]]
  branch = "master"
  name = "github.com/urfave/negroni"
