// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sigchain.proto

/*
Package messages is a generated protocol buffer package.

It is generated from these files:
	sigchain.proto

It has these top-level messages:
	Signed
	NewDevice
	Link
*/
package messages

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Signed struct {
	Body      []byte `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	Signature []byte `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	PublicKey []byte `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
}

func (m *Signed) Reset()                    { *m = Signed{} }
func (m *Signed) String() string            { return proto.CompactTextString(m) }
func (*Signed) ProtoMessage()               {}
func (*Signed) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Signed) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *Signed) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *Signed) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

type NewDevice struct {
	Name      string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	PublicKey []byte `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	FCMToken  string `protobuf:"bytes,3,opt,name=FCM_token,json=FCMToken" json:"FCM_token,omitempty"`
}

func (m *NewDevice) Reset()                    { *m = NewDevice{} }
func (m *NewDevice) String() string            { return proto.CompactTextString(m) }
func (*NewDevice) ProtoMessage()               {}
func (*NewDevice) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *NewDevice) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NewDevice) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func (m *NewDevice) GetFCMToken() string {
	if m != nil {
		return m.FCMToken
	}
	return ""
}

type Link struct {
	Prev           []byte `protobuf:"bytes,1,opt,name=prev,proto3" json:"prev,omitempty"`
	SequenceNumber uint32 `protobuf:"varint,2,opt,name=sequence_number,json=sequenceNumber" json:"sequence_number,omitempty"`
	// Types that are valid to be assigned to Body:
	//	*Link_NewDevice
	Body isLink_Body `protobuf_oneof:"body"`
}

func (m *Link) Reset()                    { *m = Link{} }
func (m *Link) String() string            { return proto.CompactTextString(m) }
func (*Link) ProtoMessage()               {}
func (*Link) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type isLink_Body interface {
	isLink_Body()
}

type Link_NewDevice struct {
	NewDevice *NewDevice `protobuf:"bytes,3,opt,name=new_device,json=newDevice,oneof"`
}

func (*Link_NewDevice) isLink_Body() {}

func (m *Link) GetBody() isLink_Body {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *Link) GetPrev() []byte {
	if m != nil {
		return m.Prev
	}
	return nil
}

func (m *Link) GetSequenceNumber() uint32 {
	if m != nil {
		return m.SequenceNumber
	}
	return 0
}

func (m *Link) GetNewDevice() *NewDevice {
	if x, ok := m.GetBody().(*Link_NewDevice); ok {
		return x.NewDevice
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Link) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Link_OneofMarshaler, _Link_OneofUnmarshaler, _Link_OneofSizer, []interface{}{
		(*Link_NewDevice)(nil),
	}
}

func _Link_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Link)
	// body
	switch x := m.Body.(type) {
	case *Link_NewDevice:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.NewDevice); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Link.Body has unexpected type %T", x)
	}
	return nil
}

func _Link_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Link)
	switch tag {
	case 3: // body.new_device
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(NewDevice)
		err := b.DecodeMessage(msg)
		m.Body = &Link_NewDevice{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Link_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Link)
	// body
	switch x := m.Body.(type) {
	case *Link_NewDevice:
		s := proto.Size(x.NewDevice)
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

func init() {
	proto.RegisterType((*Signed)(nil), "messages.Signed")
	proto.RegisterType((*NewDevice)(nil), "messages.NewDevice")
	proto.RegisterType((*Link)(nil), "messages.Link")
}

func init() { proto.RegisterFile("sigchain.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 253 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0x4d, 0x2d, 0xa1, 0x3b, 0x6a, 0x85, 0xf1, 0x12, 0x50, 0x41, 0x72, 0xd1, 0x53, 0x0e,
	0xea, 0x27, 0xb0, 0x52, 0x04, 0x6d, 0x0f, 0xab, 0x17, 0xf1, 0x10, 0xf2, 0x67, 0x88, 0x4b, 0xcc,
	0x24, 0x66, 0x93, 0x96, 0x1c, 0xfd, 0xe6, 0x92, 0x09, 0x51, 0xc8, 0xed, 0xcd, 0x1b, 0xe6, 0x37,
	0x8f, 0x07, 0x4b, 0x6b, 0xb2, 0xe4, 0x33, 0x32, 0x1c, 0x54, 0x75, 0xd9, 0x94, 0xb8, 0x28, 0xc8,
	0xda, 0x28, 0x23, 0xeb, 0xbf, 0x83, 0xfb, 0x6a, 0x32, 0xa6, 0x14, 0x11, 0xe6, 0x71, 0x99, 0x76,
	0x9e, 0x73, 0xe5, 0xdc, 0x1c, 0x6b, 0xd1, 0x78, 0x01, 0xca, 0x9a, 0x8c, 0xa3, 0xa6, 0xad, 0xc9,
	0x9b, 0xc9, 0xe2, 0xdf, 0xc0, 0x4b, 0x80, 0xaa, 0x8d, 0xbf, 0x4c, 0x12, 0xe6, 0xd4, 0x79, 0x87,
	0xc3, 0x7a, 0x70, 0x9e, 0xa9, 0xf3, 0x3f, 0x40, 0x6d, 0x69, 0xff, 0x48, 0x3b, 0x93, 0x50, 0x4f,
	0xe7, 0xa8, 0x20, 0xa1, 0x2b, 0x2d, 0x7a, 0x72, 0x3f, 0x9b, 0xdc, 0xe3, 0x39, 0xa8, 0xf5, 0x6a,
	0x13, 0x36, 0x65, 0x4e, 0x2c, 0x74, 0xa5, 0x17, 0xeb, 0xd5, 0xe6, 0xad, 0x9f, 0xfd, 0x1f, 0x07,
	0xe6, 0x2f, 0x86, 0xf3, 0x1e, 0x5c, 0xd5, 0xb4, 0x1b, 0x63, 0xf7, 0x1a, 0xaf, 0xe1, 0xd4, 0xd2,
	0x77, 0x4b, 0x9c, 0x50, 0xc8, 0x6d, 0x11, 0x53, 0x2d, 0xf4, 0x13, 0xbd, 0x1c, 0xed, 0xad, 0xb8,
	0x78, 0x0f, 0xc0, 0xb4, 0x0f, 0x53, 0xc9, 0x28, 0x3f, 0x8e, 0x6e, 0xcf, 0x82, 0xb1, 0x9c, 0xe0,
	0x2f, 0xfe, 0xd3, 0x81, 0x56, 0x3c, 0x0e, 0x0f, 0xee, 0xd0, 0x54, 0xec, 0x4a, 0x99, 0x77, 0xbf,
	0x01, 0x00, 0x00, 0xff, 0xff, 0x30, 0x1f, 0x9f, 0x4d, 0x5e, 0x01, 0x00, 0x00,
}
